
# mysql
spring:
  datasource:
#    url:  ${egw.datasource.url:jdbc:mysql://usermanagement.cofnhdktryla.us-east-1.rds.amazonaws.com:3306/usermanagement}
    url: jdbc:mysql://localhost:3306/usermanager
    username: admin
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto:
        update

server:
  port: 8081